version: "{build}"

clone_folder: c:\gopath\src\github.com\itchyny\bed

environment:
  GOPATH: c:\gopath
  GO111MODULE: on

install:
  - go version
  - go env

build_script:
  - go build ./cmd/...

test_script:
  - go test -v ./...
  - go vet ./...

deploy: false
